#pragma once
#include <string>
enum LanguageId {
    LANGID_ENGLISH = 0,
    LANGID_CHINESE = 1,
    LANGID_COUNT
};
// String IDs for UI text
enum StringId {
    STR_UTC_TIME = 0,
    STR_LAT,
    STR_LON,
    STR_AZ,
    STR_ALT,
    STR_FOV,
    STR_DEG,
    STR_DIST_AU,
    STR_DIST_LY,
    STR_DIST_UNKNOWN,
    STR_MAG,
    STR_TYPE_STAR,
    STR_TYPE_PLANET,
    STR_TYPE_MOON,
    STR_TYPE_SATELLITE,
    STR_TYPE_DEEPSKY,
    STR_TYPE_SUN,
    STR_TYPE_COMET,
    STR_TYPE_GALAXY,
    STR_TYPE_NEBULA,
    STR_TYPE_OPENCLUSTER,
    STR_TYPE_GLOBULARCLUSTER,
    STR_TYPE_PLANETARYNEBULA,
    STR_TYPE_SUPERNOVAREMNANT,
    STR_SELECTED,
    STR_NONE,
    STR_HELP_1,
    STR_HELP_2,
    STR_HELP_3,
    STR_HELP_4,
    STR_HELP_5,
    STR_HELP_6,
    STR_CELESTIAL_EQUATOR,
    STR_ECLIPTIC,
    STR_GALACTIC_EQUATOR,
    STR_ABOUT_TITLE,
    STR_ABOUT_VERSION,
    STR_ABOUT_DESC1,
    STR_ABOUT_DESC2,
    STR_ABOUT_DESC3,
    STR_ABOUT_FEATURES,
    STR_ABOUT_F1,
    STR_ABOUT_F2,
    STR_ABOUT_F3,
    STR_ABOUT_F4,
    STR_ABOUT_F5,
    STR_ABOUT_CLOSE,
    STR_DIR_N,
    STR_DIR_E,
    STR_DIR_S,
    STR_DIR_W,
    STR_COUNT
};
// English strings
static const char* g_str_en[] = {
    "UTC ",
    "Lat:",
    "Lon:",
    "Az:",
    "Alt:",
    "FOV:",
    " deg",
    "Dist:%.6f AU",
    "Dist:%.2f ly",
    "Dist:Unknown",
    "  Mag:%.2f",
    "Star",
    "Planet",
    "Moon",
    "Satellite",
    "DeepSky",
    "Sun",
    "Comet",
    "Galaxy",
    "Nebula",
    "Open Cluster",
    "Globular Cluster",
    "Planetary Nebula",
    "Supernova Remnant",
    "Selected: ",
    "None",
    "Arrow Keys: Pan",
    "+/-: Zoom",
    "Click: Select Object",
    "ESC: Exit",
    "L: Language / H: Help / T: Labels",
    "A: About",
    "Celestial Equator",
    "Ecliptic",
    "Galactic Equator",
    "Star Seeker",
    "Repo: https://github.com/ZZCjas/StarSeeker",
    "An open-source real-time sky observation tool.",
    "View stars, planets, deep sky objects",
    "and satellites from any location on Earth.",
    "Features:",
    "- Stars and deep sky objects",
    "- Solar system planets and Moons",
    "- Satellite tracking",
    "- Multi-language support",
    "- Customizable celestial body data",
    "Press A to close",
    "N",
    "E",
    "S",
    "W",
};
// Chinese strings
static const char* g_str_zh[] = {
    "UTC ",
    "纬度:",
    "经度:",
    "方位:",
    "高度:",
    "视场:",
    " 度",
    "距离:%.6f 天文单位",
    "距离:%.2f 光年",
    "距离:未知",
    "  星等:%.2f",
    "恒星",
    "行星",
    "月球",
    "人造卫星",
    "深空天体",
    "太阳",
    "彗星",
    "星系",
    "星云",
    "疏散星团",
    "球状星团",
    "行星状星云",
    "超新星遗迹",
    "选中: ",
    "无",
    "方向键: 移动视角",
    "+/-: 缩放",
    "点击: 选择天体",
    "ESC: 退出",
    "L: 语言 / H: 帮助 / T: 标签",
    "A: 关于",
    "天球赤道",
    "黄道",
    "银道",
    "Star Seeker 星图",
    "仓库：https://github.com/ZZCjas/StarSeeker",
    "一个开源的实时星图软件。",
    "可查看恒星、行星、卫星、深空天体",
    "以及人造卫星，支持任意观测地点。",
    "功能特点:",
    "- 恒星与深空天体",
    "- 太阳系行星与卫星",
    "- 人造卫星轨道计算",
    "- 多语言支持",
    "- 可自定义的天体数据",
    "按 A 键关闭",
    "北",
    "东",
    "南",
    "西",
};
static inline const char* get_str(StringId id, LanguageId lang) {
    if (id < 0 || id >= STR_COUNT) return "";
    if (lang == LANGID_CHINESE) return g_str_zh[id];
    return g_str_en[id];
}
